### PR TITLE
Expose TaskLaunchRequest as a function

### LINKED ISSUE #54: TaskLaunchRequestIntegrationTests failing
```
[ERROR] dataflowTaskLaunchRequestWithTaskLaunchRequestContextProvider(org.springframework.cloud.stream.app.tasklaunchrequest.TaskLaunchRequestIntegrationTests)  Time elapsed: 0.156 s  <<< ERROR!
org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'binderFactory' defined in class path resource [org/springframework/cloud/stream/test/binder/TestSupportBinderAutoConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.cloud.stream.test.binder.TestSupportBinderAutoConfiguration; factoryMethodName=binderFactory; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/cloud/stream/test/binder/TestSupportBinderAutoConfiguration.class]] for bean 'binderFactory': There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=bindingServiceConfiguration; factoryMethodName=binderFactory; initMethodName=null; destroyMethodName=(inferred); defined in org.springframework.cloud.stream.config.BindingServiceConfiguration] bound.
	at org.springframework.cloud.stream.app.tasklaunchrequest.TaskLaunchRequestIntegrationTests.dataflowTaskLaunchRequestWithTaskLaunchRequestContextProvider(TaskLaunchRequestIntegrationTests.java:114)

[ERROR] dataflowTaskLaunchRequestWithArgsAndDeploymentProperties(org.springframework.cloud.stream.app.tasklaunchrequest.TaskLaunchRequestIntegrationTests)  Time elapsed: 0.122 s  <<< ERROR!
org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'binderFactory' defined in class path resource [org/springframework/cloud/stream/test/binder/TestSupportBinderAutoConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.cloud.stream.test.binder.TestSupportBinderAutoConfiguration; factoryMethodName=binderFactory; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/cloud/stream/test/binder/TestSupportBinderAutoConfiguration.class]] for bean 'binderFactory': There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=bindingServiceConfiguration; factoryMethodName=binderFactory; initMethodName=null; destroyMethodName=(inferred); defined in org.springframework.cloud.stream.config.BindingServiceConfiguration] bound.
	at org.springframework.cloud.stream.app.tasklaunchrequest.TaskLaunchRequestIntegrationTests.dataflowTaskLaunchRequestWithArgsAndDeploymentProperties(TaskLaunchRequestIntegrationTests.java:74)

[INFO] Running org.springframework.cloud.stream.app.tasklaunchrequest.TaskLaunchRequestPropertiesTests
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.133 s - in org.springframework.cloud.stream.app.tasklaunchrequest.TaskLaunchRequestPropertiesTests
[INFO] Running org.springframework.cloud.stream.app.tasklaunchrequest.DeploymentPropertiesParserTests
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.springframework.cloud.stream.app.tasklaunchrequest.DeploymentPropertiesParserTests
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   TaskLaunchRequestIntegrationTests.dataflowTaskLaunchRequestWithArgsAndDeploymentProperties:74 » BeanDefinitionOverride
[ERROR]   TaskLaunchRequestIntegrationTests.dataflowTaskLaunchRequestWithTaskLaunchRequestContext:92 » BeanDefinitionOverride
[ERROR]   TaskLaunchRequestIntegrationTests.dataflowTaskLaunchRequestWithTaskLaunchRequestContextProvider:114 » BeanDefinitionOverride
[INFO]
[ERROR] Tests run: 11, Failures: 0, Errors: 3, Skipped: 0
```

### LINKED ISSUE #60: Implement TaskLaunchRequest transformation as a function
Provide support for any component to output a  TaskLaunchRequest via function composition.

### PR DESCRIPTION
**Pull request by dturanski**
This Fixes #60 also fixes #54.  This allows any app to use function composition to emit a taskLaunchRequest.

### CODE REVIEW

File: common/app-starters-security-common/my-logfile [hunk 1]
```diff
@@ -0,0 +1,379 @@
+2018-11-19 17:45:02.799  INFO 9367 --- [main] entSecurityDisabledAuthorizedAccessTests : Starting AppStarterWebSecurityTests.SecurityEnabledManagementSecurityDisabledAuthorizedAccessTests on ultrafox.local with PID 9367 (started by dturanski in /Users/dturanski/dev/spring-cloud-stream-app-starters/core/common/app-starters-security-common)
```
Comment (artembilan) [inline common/app-starters-security-common/my-logfile]: Why do we need this `my-logfile` in the repo?

File: common/app-starters-task-launch-request-common/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/DataFlowTaskLaunchRequestAutoConfiguration.java [hunk 2]
```diff
@@ -50,10 +51,16 @@ public DataFlowTaskLaunchRequestAutoConfiguration(DataflowTaskLaunchRequestPrope
 	}
 
 	@Bean
-	public TaskLaunchRequestTransformer taskLaunchRequestTransformer() {
+	public Function<Message<?>, Message<DataFlowTaskLaunchRequest>> taskLaunchRequest() {
 		return message -> dataflowTaskLaunchRequest(message);
 	}
 
+	@Deprecated
```
Comment (artembilan) [inline common/app-starters-task-launch-request-common/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/DataFlowTaskLaunchRequestAutoConfiguration.java]: Why can't we just remove this altogether?

Comment (dturanski) [reply common/app-starters-task-launch-request-common/src/main/java/org/springframework/cloud/stream/app/tasklaunchrequest/DataFlowTaskLaunchRequestAutoConfiguration.java]: Currently SFTP dataflow source needs that. I plan to refactor that later, then we can remove this.
